export enum ConfigEnum {
  HOST = 'HOST',
  PORT = 'PORT',
  DB_URL = 'DB_URL',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION = 'JWT_EXPIRATION',
  FAST2SMS_AUTH = 'FAST2SMS_AUTH',
  RAZORPAY_KEY = 'RAZORPAY_KEY',
  RAZORPAY_SECRET = 'RAZORPAY_SECRET',
}
